sudo: required

services:
  - docker

script:
  - |
    export IMAGE=cusspvz/autotune:latest &&
    docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD" &&
    docker build -t ${IMAGE} . &&
    docker push ${IMAGE} &&
    exit 0 || exit 1

branches:
  only:
    - master
